// Builds frontend/dist for direct upload:
//   - copies static assets
//   - merges functions/api/*.js into a single _worker.js router (Pages advanced mode)
const fs = require("fs");
const path = require("path");

const ROOT = __dirname;
const DIST = path.join(ROOT, "dist");
const FN = path.join(ROOT, "functions", "api");

const STATIC = ["index.html", "app.js", "styles.css"];

function rmrf(p) { if (fs.existsSync(p)) fs.rmSync(p, { recursive: true, force: true }); }
rmrf(DIST);
fs.mkdirSync(DIST, { recursive: true });

for (const f of STATIC) fs.copyFileSync(path.join(ROOT, f), path.join(DIST, f));

// --- merge functions (each module wrapped in its own scope: they all declare helpers like `authed`) ---
const files = fs.readdirSync(FN).filter((f) => f.endsWith(".js"));
let body = "";
const routes = {};
for (const f of files) {
  const name = f.replace(/\.js$/, "");           // e.g. "generate"
  let src = fs.readFileSync(path.join(FN, f), "utf8");
  const methods = [];
  src = src.replace(/export\s+async\s+function\s+onRequest(Get|Post|Put|Delete|Options)\b/g,
    (m, meth) => { methods.push(meth.toUpperCase()); return `async function onRequest${meth}`; });
  src = src.replace(/^export\s+default[\s\S]*?;$/gm, "");
  src = src.replace(/^export\s+/gm, "");
  const exports = methods.map((m) => `"${m}": onRequest${m[0] + m.slice(1).toLowerCase()}`).join(", ");
  body += `\n/* ---- ${f} ---- */\nconst mod_${name} = (() => {\n${src}\nreturn { ${exports} };\n})();\n`;
  routes["/api/" + name] = `mod_${name}`;
}

const worker = `// AUTO-GENERATED by frontend/build.js — do not edit by hand.
${body}

const ROUTES = {
${Object.entries(routes).map(([p, mod]) => `  "${p}": ${mod},`).join("\n")}
};

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    const route = ROUTES[url.pathname];
    if (route) {
      if (request.method === "OPTIONS")
        return new Response(null, { status: 204, headers: {
          "Access-Control-Allow-Origin": "*",
          "Access-Control-Allow-Headers": "Content-Type, x-access-key",
          "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
        }});
      const fn = route[request.method];
      if (!fn) return Response.json({ error: "method not allowed" }, { status: 405 });
      try { return await fn({ request, env, ctx }); }
      catch (e) { return Response.json({ error: String(e && e.message || e) }, { status: 500 }); }
    }
    if (url.pathname === "/__diag") {
      const gh = await fetch("https://api.github.com/repos/" + (env.GITHUB_REPO || "?"), {
        headers: { Authorization: "Bearer " + (env.GITHUB_PAT || ""), Accept: "application/vnd.github+json", "User-Agent": "peter-video-maker" },
      }).then((r) => r.status).catch((e) => "err:" + e.message);
      return Response.json({
        ok: true,
        hasAssets: !!env.ASSETS,
        routes: Object.keys(ROUTES),
        envKeys: Object.keys(env),
        accessKeyLen: (env.ACCESS_KEY || "").length,
        patLen: (env.GITHUB_PAT || "").length,
        repo: env.GITHUB_REPO || null,
        callbackSecretLen: (env.CALLBACK_SECRET || "").length,
        d1: !!env.DB,
        githubReadStatus: gh,
      });
    }
    try {
      if (!env.ASSETS) return new Response("no ASSETS binding", { status: 500 });
      return await env.ASSETS.fetch(request);
    } catch (e) {
      return Response.json({ error: "assets fetch failed", hasAssets: !!env.ASSETS, msg: String(e && e.message || e) }, { status: 500 });
    }
  },
};
`;
fs.writeFileSync(path.join(DIST, "_worker.js"), worker);

console.log("dist files:", fs.readdirSync(DIST).join(", "));
console.log("routes:", Object.keys(routes).join(", "));
